language: go

go:
- "1.11.1"

before_install:
- pip install --user codecov

install:
- make dependencies

script:
- make test-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- make packages

deploy:
  provider: releases
  api_key:
    secure: QxxwYJQFiJGoZhmbIYYWj8+KlfDuN5etKyybb8Y47SljKKj5bKP1OWwOQa8Hp9Vmpss2N7vEKMg93CkFm9g+Xo6bdfRbJmYs0qu9OyLjQVB5xwBmbUmdy1aqeBYFielgHdwLNC/XXIppm9N+ShBXvq2Y61YExWLLZfoF2mWZi8oVHiIuA+ViI7OzsYjAa8VNVWYqRdeIj2QlgfyvvAvjz8UwwQQULV1N3Mt7YAJ1ALZyGlCfSdE7hyu+eD8xcuBNE93/FwmDQPriMx2mdCQITWaGbDJyrPuM1U7XZaEY4k32sDwkwbC+dQck6LCMJiqw91B8559jAvRjbV+uZf8yN/9Q4Tv+xmbG+EESX2yZIcfWTO9dzrdNFn38xNZMqoNv5dhNEA3xdzyW1R2GFTWP5IphRWidS64ECpb/6f8lSLqCyBGOUTmooxfN+DRW0Yq7qAqlhQYEiAqzt9grMGA8nADi/QKuAT/dNl2vGcHEHIqEvlLUbM200bmCXJhq/mFmPYYLV9N+QrvcwhmgQJipBT5IrEMkPMgWmksxjDHnhsIkW/09Cna50dLqCIZ/SMZkdP9DnlfACDOK0FECjOmhy5FHG/VfU7HNGj42YU5cR0kOHWIasR6vp6lPR6i+MjoeU6voH7zEQRwsEaQ62HtSxuI/ksf6/1s5aU4+QgkvKC0=
  file:
    - artifacts/mortadelo_${TRAVIS_TAG}_darwin_amd64.tgz
    - artifacts/mortadelo_${TRAVIS_TAG}_linux_amd64.tgz
    - artifacts/mortadelo_${TRAVIS_TAG}_windows_amd64.tgz
  skip_cleanup: true
  on:
    repo: ivanfoo/mortadelo
    tags: true
